# Generated by Django 5.0.6 on 2025-04-22 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="آدرس")),
                (
                    "phone",
                    models.BigIntegerField(blank=True, null=True, verbose_name="تلفن"),
                ),
                ("fax", models.IntegerField(blank=True, null=True, verbose_name="فکس")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("copy_right", models.TextField(verbose_name="متن کپی رایت سایت")),
                ("about_us_text", models.TextField(verbose_name="متن درباره ما سایت")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(
                        help_text="یک بنر بارگذاری کنید",
                        upload_to="banner/images/",
                        verbose_name="بنر",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banner/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="برای اسلاید توضیحی بنویسید",
                        max_length=255,
                        null=True,
                        verbose_name="متن جایگزین بنر",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="آدرس مورد نظر برای وقتی که روی بنر کلیک می\u200cشود",
                        null=True,
                        verbose_name="آدرس URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="عکس اصلی"),
                ),
                (
                    "position",
                    models.IntegerField(blank=True, null=True, verbose_name="جایگاه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="نام اسلایدر"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Social_Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="صفحه اینشتاگرام"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, null=True, verbose_name="صفحه ی فیسبوک"
                    ),
                ),
                (
                    "whatsapp",
                    models.IntegerField(blank=True, null=True, verbose_name="واتساپ"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="توییتر"),
                ),
                (
                    "telegram",
                    models.IntegerField(blank=True, null=True, verbose_name=""),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, null=True, verbose_name="یوتیوب"),
                ),
                (
                    "aparat",
                    models.URLField(blank=True, null=True, verbose_name="اپارات"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "Tag_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="مدل تگ"
                    ),
                ),
                (
                    "Content_Id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شناسه_محتوا"
                    ),
                ),
                (
                    "tag_url",
                    models.URLField(
                        blank=True,
                        help_text="یک آدرس برای تگ بارگذاری کنید",
                        null=True,
                        verbose_name="آدرس تگ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(
                        help_text="یک اسلاید بارگذاری کنید",
                        upload_to="slides/images/",
                        verbose_name="اسلاید",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="slides/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="ادرس مقصد"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="برای اسلاید توضیحی بنویسید",
                        max_length=255,
                        null=True,
                        verbose_name="متن جایگزین عکس",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="عکس اصلی"),
                ),
                (
                    "position",
                    models.IntegerField(blank=True, null=True, verbose_name="جایگاه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="site_info.slider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rate",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="میزان رضایت شما از سایت هم ارام",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "position",
                    models.IntegerField(blank=True, null=True, verbose_name="جایگاه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                ("data_ids", models.JSONField(blank=True, null=True)),
                (
                    "SectionType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectiontype",
                        to="site_info.sectiontype",
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="site_info.tabs",
                    ),
                ),
            ],
        ),
    ]
