# Generated by Django 5.0.6 on 2025-04-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="blog-cat/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog-cat/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="نام کارگاه")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ برگزاری"
                    ),
                ),
                (
                    "locations",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="محل برگزاری",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="قیمت اولیه"
                    ),
                ),
                ("discount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="قیمت نهایی"
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "page_meta",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="متای صفحه",
                    ),
                ),
                (
                    "meta_descriptions",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متای صفحه",
                    ),
                ),
                (
                    "canolically",
                    models.URLField(blank=True, null=True, verbose_name="کنولیکال"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="workshops/videos/",
                        verbose_name="یدیوی معرفی",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctors.doctor",
                        verbose_name="مدرس",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="WorkShop", to="tag.tag", verbose_name="تگ بلاگ"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Psychology_workshops.workshopcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisterWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=12, verbose_name="شماره همراه"),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "video",
                    models.FileField(
                        upload_to="workshops/register/videos", verbose_name="ویدیو"
                    ),
                ),
                (
                    "work_shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Psychology_workshops.workshop",
                        verbose_name="ورکشاپ",
                    ),
                ),
            ],
        ),
    ]
