# Generated by Django 5.0.6 on 2025-04-22 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="کد دسته\u200cبندی"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="نام دسته\u200cبندی"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی MBTI",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای MBTI",
            },
        ),
        migrations.CreateModel(
            name="MBTIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="شناسه کاربر"
                    ),
                ),
                ("mbti_type", models.CharField(max_length=4, verbose_name="نوع MBTI")),
                ("scores", models.JSONField(verbose_name="امتیازات دسته\u200cها")),
                ("description", models.TextField(verbose_name="توضیحات شخصیت")),
                ("analysis", models.TextField(verbose_name="تحلیل نتیجه")),
                (
                    "suggestions",
                    models.TextField(verbose_name="پیشنهادات برای توسعه شخصیتی"),
                ),
            ],
            options={
                "verbose_name": "نتیجه تست MBTI",
                "verbose_name_plural": "نتایج تست MBTI",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان تست")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات تست"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stress", "استرس"),
                            ("anxiety", "اضطراب"),
                            ("depression", "افسردگی"),
                        ],
                        max_length=100,
                        verbose_name="دسته\u200cبندی تست",
                    ),
                ),
                (
                    "low_threshold",
                    models.PositiveIntegerField(
                        default=10, verbose_name="آستانه پایین"
                    ),
                ),
                (
                    "medium_threshold",
                    models.PositiveIntegerField(
                        default=20, verbose_name="آستانه متوسط"
                    ),
                ),
            ],
            options={
                "verbose_name": "تست",
                "verbose_name_plural": "تست\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="متن سوال")),
                (
                    "weight",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="وزن سوال",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Psychological_test.category",
                        verbose_name="دسته\u200cبندی MBTI",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="متن گزینه")),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز گزینه",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="Psychological_test.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزینه",
                "verbose_name_plural": "گزینه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="نام"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="test/pictures", verbose_name="عکس"),
                ),
                (
                    "web_photo",
                    models.ImageField(
                        upload_to="test/pictures/logo", verbose_name="لوگو"
                    ),
                ),
                ("short_description", models.TextField(verbose_name="توضیحات کوتاه")),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="عنوان در url"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="قیمت")),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "page_meta",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="متای صفحه",
                    ),
                ),
                (
                    "meta_descriptions",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متای صفحه",
                    ),
                ),
                (
                    "canolically",
                    models.URLField(blank=True, null=True, verbose_name="کنولیکال"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ اپدیت"),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="رایگان")),
                ("no_index", models.BooleanField(default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="TestCategory",
                        to="tag.tag",
                        verbose_name="تگ بلاگ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResultUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_score",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("detail_test", models.JSONField(verbose_name="پاسخ با جزییات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("chart_content", models.JSONField(verbose_name="نمودار نمایشی")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.testcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "short_result",
                    models.CharField(max_length=500, verbose_name="پاسخ کوتاه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.testcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="عنوان"
                    ),
                ),
                ("long_result", models.TextField(verbose_name="پاسخ کامل")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="psychology/pic/", verbose_name="عکس"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.testcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "short_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.typetest",
                        verbose_name="پاسخ کوتاه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="شناسه کاربر"),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.choice",
                        verbose_name="گزینه انتخابی",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Psychological_test.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ کاربر",
                "verbose_name_plural": "پاسخ\u200cهای کاربران",
                "unique_together": {("user_id", "question")},
            },
        ),
    ]
