# Generated by Django 5.0.6 on 2025-04-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="client_cash_in",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=150, verbose_name="شرح ورودی"
                    ),
                ),
                ("price", models.BigIntegerField(default=0, verbose_name="مبلغ")),
                (
                    "method",
                    models.CharField(
                        default="انلاین", max_length=6, verbose_name="روش پرداخت"
                    ),
                ),
                (
                    "online_ret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="لینک ارجاع",
                    ),
                ),
                ("gen_date", models.DateTimeField(verbose_name="تاریخ ایجادفاکتور")),
                (
                    "confirmer_is_gate",
                    models.BooleanField(
                        default=False,
                        verbose_name="تایید کننده ی پرداخت درگاه بانکی است؟",
                    ),
                ),
                (
                    "confirm_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تایید دریافت وجه"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, verbose_name="ایا پرداخت شده است؟"
                    ),
                ),
                (
                    "self_type",
                    models.CharField(
                        default="main", max_length=10, verbose_name="نوع سند مالی"
                    ),
                ),
                (
                    "obj_rel",
                    models.CharField(
                        max_length=10, verbose_name="فاکتور برای چه خدمتی است"
                    ),
                ),
                ("obj_rel_id", models.BigIntegerField(verbose_name="کد خدمت")),
                (
                    "lawer_share",
                    models.BigIntegerField(default=0, verbose_name="سهم پزشک"),
                ),
                (
                    "website_shar",
                    models.BigIntegerField(default=0, verbose_name="سهم وبسایت"),
                ),
                (
                    "used_tariff",
                    models.BigIntegerField(default=0, verbose_name="تعرفه اعمال شده"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="کاربری که فاکتور برای او صادر شده است",
                    ),
                ),
                (
                    "confirm_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر تایید کننده",
                    ),
                ),
                (
                    "gen_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gen_user_to_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر ایجاد کننده فاکتور",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="idpay_main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.TextField()),
                ("payment_id", models.TextField()),
                ("amount", models.IntegerField(default="-")),
                ("card_number", models.TextField(default="****")),
                ("id_pay_track_id", models.IntegerField(default=0)),
                ("bank_track_id", models.TextField(default=0)),
                ("status", models.IntegerField(default=0)),
                (
                    "ret_url",
                    models.CharField(
                        default="", max_length=250, verbose_name="مسیر برگشت"
                    ),
                ),
                (
                    "cash_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.client_cash_in",
                        verbose_name="فاکتور مربوطه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.BigIntegerField(verbose_name="موجودی")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBalanceDescriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descriptions",
                    models.CharField(default="", max_length=500, verbose_name="شرح"),
                ),
                ("price", models.IntegerField(verbose_name="مبلغ")),
                ("type", models.CharField(max_length=1, verbose_name="نوع تراکنش")),
                (
                    "transfer_kind",
                    models.CharField(
                        default="0", max_length=5, verbose_name="نحوه انتقال"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاریر",
                    ),
                ),
            ],
        ),
    ]
