# Generated by Django 5.0.6 on 2025-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileManagers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="filemanager/%Y/%m/%d/")),
                ("title", models.CharField(max_length=30)),
            ],
        ),
    ]
