# Generated by Django 5.0.6 on 2025-04-22 17:12

import datetime
import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Panel_Admin", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailableTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "count_remaining",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ادرس درخواست کننده",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت به تومان"
                    ),
                ),
                (
                    "expired_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تاریخ انقضا سفارش"
                    ),
                ),
                ("payment_date", models.DateTimeField(default=datetime.datetime.now)),
                ("is_paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PackageService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام سرویس")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(seconds=1800)
                            )
                        ]
                    ),
                ),
                (
                    "first_price",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="قیمت محصول"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قیمت نهایی به تومان",
                    ),
                ),
                (
                    "discount_price",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="تخفیف بر حسب تومان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="TOMAN",
                        max_length=10,
                        null=True,
                        verbose_name="واحد پول",
                    ),
                ),
                ("count_metting", models.IntegerField(blank=True, null=True)),
                (
                    "free_metting",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد جلسات رایگان"
                    ),
                ),
                (
                    "visite_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online", "انلاین"),
                            ("person", "حضوری"),
                            ("call", "تلفنی"),
                        ],
                        max_length=200,
                        null=True,
                        verbose_name="نوع ویزیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("seo", models.BooleanField(default=False, verbose_name="سئو")),
                ("client", models.BooleanField(default=False, verbose_name="کلاینت")),
                (
                    "expert",
                    models.BooleanField(default=False, verbose_name="کارشناس فروش"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=300, verbose_name="نام و نام خانوادگی"),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="شماره همراه"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("W", "زن")], max_length=100
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentGatewayVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("Stripe", "Stripe"),
                            ("PayPal", "PayPal"),
                            ("Braintree", "Braintree"),
                        ],
                        max_length=50,
                    ),
                ),
                ("merchant_id", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("public_key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_id", models.CharField(max_length=255)),
                ("payment_date", models.DateTimeField(default=datetime.datetime.now)),
                ("is_successful", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeStamped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "session_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("online", "انلاین"),
                            ("person", "حضوری"),
                            ("call", "تلفنی"),
                        ],
                        max_length=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="کپن تخفیف ثبت شده",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "is_finaly",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="قرار ملاقات نهایی شده؟",
                    ),
                ),
                (
                    "is_reserved",
                    models.BooleanField(
                        default=False, verbose_name="رزو شده توسط پزشک"
                    ),
                ),
                (
                    "is_coupon",
                    models.BooleanField(
                        default=False, verbose_name="شامل تخفیف شده است؟"
                    ),
                ),
                (
                    "booke_by_expert",
                    models.BooleanField(
                        default=False, verbose_name="رزرو شده توسط کارشناس فروش"
                    ),
                ),
                (
                    "price_approved",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت به تومان"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ موثر"),
                ),
                (
                    "coupon_submit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Panel_Admin.coupon",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "expert_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Panel_Admin.saleexpert",
                        verbose_name="ثبت شده توسط کارشناس فروش",
                    ),
                ),
            ],
        ),
    ]
