# Generated by Django 5.0.6 on 2025-04-22 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("cart", "0001_initial"),
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentfinal",
            name="factors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.myfactors",
            ),
        ),
        migrations.AddField(
            model_name="appointmentreminder",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="appointment.appointmentfinal",
            ),
        ),
        migrations.AddField(
            model_name="availabletimeslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
            ),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_packages",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_packages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordervisit",
            name="appointmentfinal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointmentfinal",
                verbose_name="ملاقات با پزشک",
            ),
        ),
        migrations.AddField(
            model_name="ordervisit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="packageservice",
            name="title_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctorcategory",
                verbose_name="موضوع مشاوره",
            ),
        ),
        migrations.AddField(
            model_name="orderpackage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_packages",
                to="appointment.packageservice",
            ),
        ),
        migrations.AddField(
            model_name="appointmentfinal",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.packageservice",
            ),
        ),
        migrations.AddField(
            model_name="patients",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="appointmentfinal",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointment.patients",
            ),
        ),
        migrations.AddField(
            model_name="paymentvisit",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="appointment.appointmentfinal",
            ),
        ),
        migrations.AddField(
            model_name="paymentvisit",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="appointment.paymentgatewayvisit",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="services_offered",
            field=models.ManyToManyField(to="appointment.packageservice"),
        ),
        migrations.AddField(
            model_name="dayoff",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="appointmentfinal",
            name="doctor_available",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="timestamped",
            name="available_time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self",
                to="appointment.availabletimeslot",
            ),
        ),
        migrations.AddField(
            model_name="timestamped",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_stamps",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="time_stamps",
            field=models.ManyToManyField(to="appointment.timestamped"),
        ),
        migrations.AddField(
            model_name="appointmentfinal",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.timestamped",
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.staffmember",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabletimeslot",
            unique_together={("doctor", "start_time", "end_time")},
        ),
        migrations.AlterUniqueTogether(
            name="timestamped",
            unique_together={("doctor", "available_time_slot", "date")},
        ),
    ]
