# Generated by Django 5.0.6 on 2025-04-21 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "Phone_Number",
                    models.CharField(
                        default="",
                        max_length=120,
                        unique=True,
                        verbose_name="شماره همراه",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="ایمیل",
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_doctor", models.BooleanField(default=False)),
                ("is_supporter", models.BooleanField(default=False)),
                ("is_doctoradmin", models.BooleanField(default=False)),
                ("is_admin_assistant", models.BooleanField(default=False)),
                ("is_abroad", models.BooleanField(default=False)),
                ("is_expert", models.BooleanField(default=False)),
                ("is_seo", models.BooleanField(default=False)),
                (
                    "confirm_otp",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                    ),
                ),
                ("confirm_otp_expiration", models.DateTimeField(null=True)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=250, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "national_code",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="کد ملی"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("اضطراب و استرس", "اضطراب و استرس"),
                            ("هیپنوتراپی", "هیپنوتراپی"),
                            ("فوبیا", "فوبیا"),
                            ("ترس", "ترس"),
                            ("روانکاوی", "روانکاوی"),
                            ("خانواده", "خانواده"),
                            ("کودک", "کودک"),
                            ("افسردگی", "افسردگی"),
                            ("تحصیلی", "تحصیلی"),
                            ("سوگواری", "سوگواری"),
                            ("خیانت", "خیانت"),
                            ("ازدواج", "ازدواج"),
                            ("طلاق", "طلاق"),
                            ("پیش از ازدواج", "پیش از ازدواج"),
                            ("جنسی و سکستراپی", "جنسی و سکستراپی"),
                            ("اعتماد به نفس", "اعتماد به نفس"),
                            ("روابط عاطفی", "روابط عاطفی"),
                            ("اعتماد", "اعتماد"),
                            ("خودشناسی", "خودشناسی"),
                            ("مهاجرت", "مهاجرت"),
                            ("زوج درمانی", "زوج درمانی"),
                            ("افکار وسواسی", "افکار وسواسی"),
                            ("درمان اعتیاد", "درمان اعتیاد"),
                            ("کودک و نوجوان", "کودک و نوجوان"),
                            ("شکست عشقی", "شکست عشقی"),
                            ("هوش عاطفی", "هوش عاطفی"),
                            ("سایر اختلالات فردی", "سایر اختلالات فردی"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="موضوع مشاوره",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="users/profile/images/",
                        verbose_name="عکس",
                    ),
                ),
                ("deaf", models.BooleanField(default=False, verbose_name="شنوا هستم")),
                (
                    "hard_hearing",
                    models.BooleanField(default=False, verbose_name="کم شنوا هستم"),
                ),
                (
                    "hearing",
                    models.BooleanField(default=False, verbose_name="نا شنوا هستم"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "upload_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/userfile",
                        verbose_name="اپلود فایل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نام کاربری",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255, unique=True)),
                ("refresh_token", models.CharField(max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_token_expiration", models.DateTimeField(null=True)),
                ("refresh_token_expiration", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
