# Generated by Django 5.0.6 on 2025-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="نام تگ"
                    ),
                ),
                (
                    "eng_title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        unique=True,
                        verbose_name="نام تگ به انگلیسی",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
            ],
        ),
    ]
