# Generated by Django 5.0.6 on 2025-04-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=300, verbose_name="نام نویسنده"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="عنوان دسته بندی مقاله"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="blog-cat/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog-cat/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogcategory",
                        verbose_name="دسته بندی والد",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="blog/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان مقاله")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="عنوان کوتاه"),
                ),
                ("content", models.TextField(verbose_name="محتوای مقاله")),
                (
                    "page_meta",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="متای صفحه",
                    ),
                ),
                (
                    "meta_descriptions",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متای صفحه",
                    ),
                ),
                (
                    "canolically",
                    models.URLField(blank=True, null=True, verbose_name="کنولیکال"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "read_time",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        null=True,
                        verbose_name="زمان خواندن مقاله",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("no_index", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.authorlist",
                        verbose_name="نویسنده ی مقاله",
                    ),
                ),
                (
                    "doctorname",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                        verbose_name="اسم دکتر",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="blog", to="tag.tag", verbose_name="تگ بلاگ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.blogcategory",
                        verbose_name="دسته بندی مقاله",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        help_text="یک عکس بارگذاری کنید",
                        upload_to="blog/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="برای عکس توضیحی بنویسید",
                        max_length=255,
                        null=True,
                        verbose_name="متن جایگزین عکس",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=360,
                        null=True,
                        verbose_name="توضیحات کوتاه",
                    ),
                ),
                (
                    "is_feature",
                    models.BooleanField(default=False, verbose_name="عکس اصلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_image",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس مقاله",
                "verbose_name_plural": "عکس های مقالات",
            },
        ),
        migrations.CreateModel(
            name="CommentsBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auther", models.CharField(max_length=20)),
                ("text", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="تایید/عدم تایید"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت در مقاله",
                "verbose_name_plural": "کامنتهای مقالات",
            },
        ),
        migrations.CreateModel(
            name="LikeBlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.IntegerField(default=0)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
