# Generated by Django 5.0.6 on 2025-04-22 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("doctors", "0001_initial"),
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="نام پادکست")),
                ("time_durations", models.IntegerField(verbose_name="مدت زمان")),
                (
                    "price",
                    models.IntegerField(default=0, verbose_name="قیمت نهایی به تومان"),
                ),
                (
                    "first_price",
                    models.IntegerField(default=0, verbose_name="قیمت اولیه"),
                ),
                (
                    "discount_price",
                    models.IntegerField(default=0, verbose_name="تخفیف بر حسب تومان"),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="رایگان است؟"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="podcasts/%Y/%m/%d",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="podcast_images/", verbose_name="تصویر پادکست"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوای پادکست")),
                (
                    "page_meta",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="متای صفحه",
                    ),
                ),
                (
                    "meta_descriptions",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متای صفحه",
                    ),
                ),
                (
                    "canolically",
                    models.URLField(blank=True, null=True, verbose_name="کنولیکال"),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ اپدیت"),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "is_validate",
                    models.BooleanField(default=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.authorlist",
                        verbose_name="نویسنده ی مقاله",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="Podcast", to="tag.tag", verbose_name="تگ پادکست"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نام کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LikePodcastPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.podcast",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentsPodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auther", models.CharField(max_length=20)),
                ("text", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="تایید/عدم تایید"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت در پادکست",
                "verbose_name_plural": "کامنتهای پادکست",
            },
        ),
        migrations.CreateModel(
            name="PodcastCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="عنوان دسته بندی پادکست"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="podcast-cat/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "web_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="podcast-cat/web-images/",
                        verbose_name="عکس فشرده وب",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.podcastcategory",
                        verbose_name="دسته بندی والد",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="podcast",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="podcast.podcastcategory",
                verbose_name="دسته بندی پادکست",
            ),
        ),
    ]
