# Generated by Django 5.0.6 on 2025-04-22 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان ویدیو")),
                (
                    "video_banner",
                    models.FileField(
                        upload_to="upload/vlog/video_banner", verbose_name="ویدیو"
                    ),
                ),
                (
                    "video_photo",
                    models.ImageField(
                        upload_to="upload/vlog/video_photo", verbose_name="بنر ویدیو"
                    ),
                ),
                (
                    "voice",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="upload/vlog/voice",
                        verbose_name="voice",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قیمت",
                    ),
                ),
                (
                    "discount_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت تخفیف خورده"
                    ),
                ),
                (
                    "final_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت نهایی"
                    ),
                ),
                (
                    "free_status",
                    models.BooleanField(default=False, verbose_name="محصول رایگان"),
                ),
                ("content", models.TextField(verbose_name="محتوای مقاله")),
                (
                    "description_author",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="upload/vlog/mp3/description_author",
                        verbose_name="توضیحات مشاور",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                ("data_file", models.IntegerField(default=0, verbose_name="حجم فایل")),
                ("Discount", models.IntegerField(default=0, verbose_name="تخفیف")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                ("view_count", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                        verbose_name="مدرس",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentsVlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auther", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vlog-comments/images/"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="vlog-comments/images/"
                    ),
                ),
                ("text_2", models.TextField()),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vlog.vlog"
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت در ولاگ",
                "verbose_name_plural": "کامنتهای ولاگها",
            },
        ),
        migrations.CreateModel(
            name="Vlog_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="عنوان دسته بندی ولاگ"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="upload/vlog/images",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="یک عکس بارگذاری کنید",
                        null=True,
                        upload_to="brand/images/",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vlog.vlog_category",
                        verbose_name="دسته بندی والد",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده ورلاگ",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vlog",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vlog.vlog_category",
                verbose_name="دسته بندی مقاله",
            ),
        ),
    ]
