# Generated by Django 5.0.6 on 2025-04-22 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("vlog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50, unique=True)),
                ("last_number", models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name="CartToCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo_transactions",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cart_cart/",
                        verbose_name="رسید کارت به کارت",
                    ),
                ),
                (
                    "total_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مبلغ واریز شده"
                    ),
                ),
                (
                    "created_transactions",
                    models.DateField(verbose_name="تاریخ تراکنیش"),
                ),
                (
                    "time_of_transactions",
                    models.DateTimeField(verbose_name="ساعت تراکنش"),
                ),
                (
                    "number_of_transactions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شماره پیگیری",
                    ),
                ),
                (
                    "cart_number",
                    models.CharField(
                        max_length=128, verbose_name="4 رقم اخر شماره کارت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "در حال بررسی"),
                            ("2", "با موفقیت انجام شده"),
                            ("3", "رد شده"),
                        ],
                        default=1,
                        max_length=150,
                        null=True,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده است؟"),
                ),
                (
                    "comment_status",
                    models.TextField(
                        blank=True, null=True, verbose_name="پاسخ وضعیت تراکنش"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartToCartForeigner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo_transactions",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carttocartForeigner/",
                        verbose_name="رسید کارت به کارت خارجی",
                    ),
                ),
                (
                    "total_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مبلغ واریز شده"
                    ),
                ),
                (
                    "link_of_transactions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="لینک تراکنش",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده است؟"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyFactors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "number_factors",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_price", models.IntegerField(blank=True, null=True)),
                ("final_pay_price", models.IntegerField(blank=True, null=True)),
                ("discounted_price", models.IntegerField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("trackId", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                ("order_item_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت محصول"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_finaly", models.BooleanField(default=False)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "package_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.packageservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vlog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vlog.vlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("قرار ملاقات با پزشک", "قرار ملاقات با پزشک"),
                            ("تست روانشناسی", "تست روانشناسی"),
                            ("کارگاه های من", "کارگاه های من"),
                            ("پادکست", "پادکست"),
                            ("ولاگ", "ولاگ"),
                        ],
                        default=1,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "final_price",
                    models.IntegerField(default=0, verbose_name="قیمت نهایی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointmentfinal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(default=0.0, verbose_name="Wallet Balance"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Charge_Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=0.0, verbose_name="Charge wallet amount"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authority", models.CharField(blank=True, max_length=255, null=True)),
                ("RefID", models.CharField(blank=True, max_length=50, null=True)),
                ("Status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "callback_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "redirect_front_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.wallet",
                    ),
                ),
            ],
        ),
    ]
