# Generated by Django 5.0.6 on 2025-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CancellApointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="قیمت")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "کارت به کارت"),
                            ("2", "به ولت اضافه شود"),
                            ("3", "رد شده توسط امور مالی"),
                        ],
                        max_length=500,
                        null=True,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "is_finaly",
                    models.BooleanField(default=False, verbose_name="انجام شده است؟"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentReporting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=250)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت گزارش شده",
                "verbose_name_plural": "کامنت های گزارش شده",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام کد"
                    ),
                ),
                (
                    "num_uses",
                    models.PositiveIntegerField(default=1, verbose_name="سقف تعداد "),
                ),
                (
                    "limit_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="سقف استفاده کاربر "
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اصلی"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="زمان شروع")),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "max_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name=" حداکثر قیمت قابل استفاده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کد های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="CouponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codetype",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نوع کد"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع کد تخفیف",
                "verbose_name_plural": "انواع کد های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="LibraryBookDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.FileField(upload_to="panel/books/", verbose_name="کتاب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="تاریخ اپدیت")),
            ],
            options={
                "verbose_name": "کتابهای پزشکی",
                "verbose_name_plural": "کتاب پزشکی",
            },
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="سن")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "زن")],
                        max_length=15,
                        verbose_name="جنسیت",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                ("content", models.TextField(null=True, verbose_name="محتوای یاداشت")),
                (
                    "reason_visit",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="علت مراجعه"
                    ),
                ),
                (
                    "diagnose",
                    models.CharField(max_length=500, verbose_name="تشخیص پزشک"),
                ),
                ("treatment_steps", models.TextField(verbose_name="مراحل درمان")),
                ("exercises", models.TextField(verbose_name="تمرین ها")),
                (
                    "upload_doc",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/%Y/%m/%d/treatment",
                        verbose_name="اپلود مدارک پزشکی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ اپدیت"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleExpert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "image_profile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="panel/expert/pictures/%Y/%m/%d",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره پرسنلی",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("", ""), ("women", "خانم"), ("men", "آقا")],
                        max_length=50,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, null=True, verbose_name="بیوگرافی"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="عنوان"
                    ),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
            ],
        ),
        migrations.CreateModel(
            name="SmsTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="اسم پوسته"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="محتوای فایل"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_goals",
                    models.TextField(verbose_name="اهداف درمانی بلند مدت و کوتاه مدت"),
                ),
                (
                    "technique_used",
                    models.TextField(verbose_name="تکنیک و رویکرد مورد استفاده"),
                ),
                (
                    "therapy_note",
                    models.TextField(verbose_name="خلاصه هر جلسه و تکالیف ارائه شده"),
                ),
                (
                    "planning_meeting",
                    models.TextField(verbose_name="برنامه ریزی جلسات آینده"),
                ),
                (
                    "therapeutic_homework",
                    models.TextField(verbose_name="تکالیف بین جلسات"),
                ),
                (
                    "progress_note",
                    models.TextField(verbose_name="بررسی پیشرفت و تغییرات در علائم"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ اپدیت"),
                ),
            ],
            options={
                "verbose_name": "فرآیندهای درمان",
                "verbose_name_plural": "فرآیند درمان",
            },
        ),
    ]
