# Generated by Django 5.0.6 on 2025-04-22 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Panel_Admin", "0001_initial"),
        ("appointment", "0001_initial"),
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellapointment",
            name="appointment_final",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointmentfinal",
                verbose_name="نوبت ثبت شده",
            ),
        ),
        migrations.AddField(
            model_name="cancellapointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctor",
                verbose_name="لغو شده توسط دکتر",
            ),
        ),
        migrations.AddField(
            model_name="cancellapointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="لغو شده توسط مریض",
            ),
        ),
        migrations.AddField(
            model_name="cancellapointment",
            name="timeslot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.timestamped",
                verbose_name="زمان رزو شده",
            ),
        ),
        migrations.AddField(
            model_name="commentreporting",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctorcomment"
            ),
        ),
        migrations.AddField(
            model_name="commentreporting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="invalid_users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="کاربران غیر مجاز"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_products",
            field=models.ManyToManyField(
                to="appointment.packageservice", verbose_name="محصولات مجاز"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Panel_Admin.coupontype",
                verbose_name="نوع کد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="librarybookdoctor",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                verbose_name="دکتر",
            ),
        ),
        migrations.AddField(
            model_name="reportuser",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                verbose_name="دکتر",
            ),
        ),
        migrations.AddField(
            model_name="reportuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاریر",
            ),
        ),
        migrations.AddField(
            model_name="saleexpert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="نام کارشناس",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="user_receiver",
            field=models.ManyToManyField(
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="پیام گیرنده",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="user_sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="پیام فرستنده",
            ),
        ),
        migrations.AddField(
            model_name="smstemplates",
            name="user_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد کننده",
            ),
        ),
        migrations.AddField(
            model_name="treatmentprocess",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                verbose_name="دکتر",
            ),
        ),
        migrations.AddField(
            model_name="treatmentprocess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاریر",
            ),
        ),
    ]
