# Generated by Django 5.0.6 on 2025-04-22 06:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cooprations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, unique=True)),
                ("eng_title", models.CharField(max_length=50, unique=True)),
                (
                    "internal_link",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="لینک داخلی"
                    ),
                ),
                (
                    "photo_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctor/logo",
                        verbose_name="لوگو",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="فیلد تحصیلی"
                    ),
                ),
                (
                    "eng_title",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="فیلد تحصیلی به زبان انگلیسی",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_profile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctor/pictures/%Y/%m/%d",
                        verbose_name="عکس",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="اسم و فامیل"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("", ""), ("women", "خانم"), ("men", "آقا")],
                        max_length=50,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "start_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="شروع فعالیت پزشکی از سال"
                    ),
                ),
                (
                    "medical_license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره نظام پزشکی"
                    ),
                ),
                (
                    "locations",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="ادرس مطب"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "video_url_meets",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک گوگل میت"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "datetime_modified",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ تغییرات"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="فعال/ غیر فعال"),
                ),
                ("view_count", models.IntegerField(default=0)),
                (
                    "rate_count",
                    models.FloatField(
                        blank=True,
                        default=4,
                        null=True,
                        verbose_name="میانگین امتیازات",
                    ),
                ),
                (
                    "page_meta",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="متای صفحه",
                    ),
                ),
                (
                    "meta_descriptions",
                    models.CharField(
                        blank=True,
                        help_text="برای صفحه  متایی بنویسید",
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات متای صفحه",
                    ),
                ),
                (
                    "canolically",
                    models.URLField(blank=True, null=True, verbose_name="کنولیکال"),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="کلمات کلیدی",
                    ),
                ),
                (
                    "cooperation_kind",
                    models.ManyToManyField(
                        max_length=50,
                        to="doctors.cooprations",
                        verbose_name="نوع همکاری",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        max_length=100, to="tag.tag", verbose_name="تگ"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نام دکتر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                ("like_count", models.IntegerField(default=0)),
                ("dislike_count", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_answers",
                        to="doctors.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="دسته بندی")),
                (
                    "eng_title",
                    models.CharField(
                        max_length=150, verbose_name="دسته بندی به انگلیسی"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=360,
                        unique=True,
                        verbose_name="عنوان در url",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="doctors.doctorcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctorcategory",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.CreateModel(
            name="DoctorComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                ("text", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "is_validated",
                    models.BooleanField(null=True, verbose_name="تایید/عدم تایید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد "
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین اپدیت"
                    ),
                ),
                ("like_count", models.IntegerField(default=0)),
                ("dislike_count", models.IntegerField(default=0)),
                (
                    "Answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctoranswer",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="doctors.doctorcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctoranswer",
            name="comments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_answers",
                to="doctors.doctorcomment",
            ),
        ),
        migrations.CreateModel(
            name="DoctorPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, null=True, verbose_name="ایمیل"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="doctors.doctor",
                        verbose_name="نام پزشک",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نام یادداشت گذارنده",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rate_Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام کاربر")),
                (
                    "rate_1",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="رضایت از نحوه مشاوره",
                    ),
                ),
                (
                    "rate_2",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="کیفیت راهنمایی",
                    ),
                ),
                (
                    "rate_3",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="نحوه برگزاری جلسه",
                    ),
                ),
                (
                    "rate_4",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="نظم جلسه مشاوره",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال /غیر فعال"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="پزشک",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.specialization",
                verbose_name="فیلد تحصیلی",
            ),
        ),
    ]
