# Generated by Django 5.0.6 on 2025-04-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("family", models.CharField(max_length=200, verbose_name="فامیل")),
                ("age", models.IntegerField(verbose_name="سن")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "زن")],
                        max_length=15,
                        verbose_name="جنسیت",
                    ),
                ),
                ("nation_code", models.IntegerField(default=0, verbose_name="کد ملی")),
                ("documents_number", models.IntegerField(verbose_name="شماره پرونده")),
                (
                    "create_visit",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد ویزیت"
                    ),
                ),
                (
                    "diagnose",
                    models.CharField(max_length=500, verbose_name="تشخیص پزشک"),
                ),
                (
                    "prescription",
                    models.TextField(max_length=1000, verbose_name="نسخه"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "upload_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/%Y/%m/%d/treatment",
                        verbose_name="اپلود مدارک پزشکی",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False, verbose_name="توسط پزشک بسته شده است؟"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                        verbose_name="پزشک معالج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
